openapi: 3.0.0
info:
  title: WithAI API
  version: "0.0.1"
servers:
  - url: https://www.getwith.ai
paths:
  /api/workflow/create:
    post:
      summary: Create Workflow
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /api/workflow/run:
    post:
      summary: Run Workflow
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  /api/workflow/{workflowID}:
    parameters:
      - name: workflowID
        in: path
        required: true
        schema:
          type: string
    get:
        summary: Get Workflow Status
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
